version: '3'

services:
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:6.0.1
        user: root
        restart: always
        volumes:
            - "${DATA_PATH}/artifactory/:/var/opt/jfrog/artifactory"
        ports:
            - 8082:8081 
            - 5002:5002
            - 5003:5003
        environment:
            - VIRTUAL_HOST=artifactory.${DOMAIN}
            - VIRTUAL_PORT=8081
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.10
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.frontend.rule=Host:artifactory.${DOMAIN}"
           - "traefik.backend=artifactory"
           - "traefik.backend.port=8081"
