version: '3'

services:
    jira:
        image: cptactionhank/atlassian-jira-software:7.10.0
        user: root
        restart: always
        volumes:
           - ${DATA_PATH}/jira/jira:/var/atlassian/jira
           - ${DATA_PATH}/jira/logs:/opt/atlassian/jira/logs
        ports:
           - 8097:8080
        environment:
           - VIRTUAL_HOST=jira.${DOMAIN}
           - VIRTUAL_PORT=8080
        networks:
          fabriq_net:
            ipv4_address: 172.8.0.11
        labels:
           - "traefik.docker.network=fabriq_net"
           - "traefik.backend=jira"
           - "traefik.frontend.rule=Host:jira.${DOMAIN}"
